app/rooms/models.py
# local modules and libraries
from app import db


# models
class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.INTEGER, primary_key=True, nullable=False)
    name = db.Column(db.VARCHAR(50), nullable=False)
    description = db.Column(db.TEXT)
    room = db.relationship('Room', backref='Category', lazy=True)

    def __repr__(self):
        return f'Category: {self.name}'


class Room(db.Model):
    __tablename__ = 'room'
    id = db.Column(db.VARCHAR(100), primary_key=True, nullable=False)
    title = db.Column(db.VARCHAR(80), index=True, nullable=False)
    description = db.Column(db.TEXT)
    image_url = db.Column(db.TEXT)
    likes = db.Column(db.INTEGER)
    room_key = db.Column(db.VARCHAR(40), unique=True)
    is_private = db.Column(db.Boolean, nullable=False , default=False)
    category = db.Column(db.INTEGER,
                         db.ForeignKey('category.id', ondelete='cascade',
                                       onupdate='cascade'),
                         nullable=False)
    rooms_pool = db.relationship('RoomsPool', backref='Room')

    def __repr__(self):
        return f'Room: {self.title}'


class Roles(db.Model):
    __tablename__ = "roles"
    id = db.Column(db.INTEGER, primary_key=True, nullable=False)
    name = db.Column(db.VARCHAR(120), nullable=False)
    description = db.Column(db.TEXT)
    rooms_pool = db.relationship('RoomsPool', backref='Roles')

    def __repr__(self):
        return f'Role: {self.name}'


class RoomsPool(db.Model):
    __tablename__ = 'roomspool'

    id = db.Column(db.INTEGER, primary_key=True, nullable=False)
    room_id = db.Column(db.VARCHAR(100), db.ForeignKey('room.id', ondelete='restrict'), nullable=False)
    user_id = db.Column(db.INTEGER, db.ForeignKey('user.id', ondelete='restrict'), nullable=False)
    role_id = db.Column(db.INTEGER, db.ForeignKey('roles.id', ondelete='restrict'), nullable=False)

    def __repr__(self):
        return f"""room_id : {self.room_id}
                   user_id : {self.user_id}
                   role_id: {self.role_id}   
        """

app/rooms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, RadioField, SubmitField, TextAreaField
from flask_wtf.file import FileField, FileRequired
from wtforms.validators import DataRequired
from flask import current_app
from .models import Category



class CreateRoom(FlaskForm):
    title = StringField('Chatroom title', validators=[DataRequired()])
    image = FileField("Upload chatroom image")
    description = TextAreaField('description', validators=[DataRequired()])
    rooms_types = RadioField(choices=[('Chatroom wil be public', 'public'), ('value2', 'private')])
    category = RadioField()

    submit = SubmitField('Create chatroom')

app/rooms/views.py
# third party libraries
import os.path

from flask import Blueprint, render_template, abort, flash
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from .forms import CreateRoom
# local modules and libraries
from .models import Room, Category, RoomsPool
from .utils import generate_room_key
from app import db

rooms = Blueprint('rooms', __name__, static_folder='static',
                  template_folder='templates',
                  static_url_path='/chatrooms')


@rooms.errorhandler(404)
def page_not_found(error):
    return render_template('404.html', title='404'), 404


@rooms.route('/chatrooms/<room_id>')
@login_required
def room(room_id):
    room_data = Room.query.filter_by(id=room_id).first()

    if room_data is None:
        abort(404)
    return 'hi there'


@rooms.route('/chatrooms/create_room', methods=['GET', 'POST'])
@login_required
def create_room():
    filename = ""
    form = CreateRoom()
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]
    if form.validate_on_submit():
        print(form.category.data)
        room_key = generate_room_key()
        image = form.image.data
        filename = secure_filename(image.filename)
        new_filename = room_key + "-" + filename
        print(new_filename)
        image.save(os.path.join(
            rooms.static_folder, 'images', new_filename
        ))

        room = Room(id=form.title.data,
                    title=form.title.data,
                    description=form.description.data,
                    image_url=new_filename,
                    room_key=room_key,
                    category=form.category.data,
                    is_private=True if form.rooms_types.data == 'private' else False
                    )
        rooms_pool = RoomsPool(room_id=form.title.data,
                               user_id=current_user.id,
                               role_id=1)

        db.session.add_all([room, rooms_pool])
        db.session.commit()
        print("you have created a new chatroom")

    return render_template('create_chatroom.html', form=form)

app/rooms/templates/chatrooms_section.html
{% block links %}

    <link rel="stylesheet" href="{{ url_for('rooms.static', filename='styles/chatroomcontainer.css') }}">

{% endblock links %}

{% block chatrooms %}
        <div class="chatrooms__container">
            {% for room in rooms %}
                <div class="chatrooms__container-chatroom" >
                    <img class="chatroom__img" src="{{ url_for('rooms.static', filename='images/{0}'.format(room.image_url))}}">
                    <div class="chatroom__content">
                        <h4 class="chatroom__content-title">{{ room.title }}</h4>
                        <p class="chatroom__content-description">{{ room.description }}</p>
                    </div>
                    <div class="chatroom__about">
                        <!-- icons likes, join, etc -->
                        <a href="#"><i class="ri-chat-2-fill"></i><span>0</span></a>
                        <a href="#"> <i class="ri-team-fill"></i><span>0</span></a>
                        {% if not room in user_rooms %}
                        <form action="/" method="POST">
                            <i class="ri-add-circle-fill"></i>
                            <input id="{{ room.id }}" type="submit" class="categories_element" value="Join" name="{{ room.id }}">
                        </form>
                        {% endif %}
                        <a href="{{ url_for('rooms.room', room_id=room.id) }}"><i class="ri-door-open-fill"></i><span>chat</span></a>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock chatrooms %}

app/rooms/templates/create_chatroom.html
{% extends "base.html" %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('rooms.static', filename='styles/create_room.css') }}">
{% endblock %}

{% block main %}

    <form class="create_room" method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="room_title">
            {{ form.title.label }}
            {{ form.title }}
        </div>

        <div class="room_image">
            {{ form.image.label(class="custom-file-upload") }}
            {{ form.image }}
        </div>

        <div class="room_description">
            {{  form.description.label}}
            {{ form.description }}
        </div>

        <div class="room_type-container">
            {{ form.csrf_token }}
            {% for room in form.rooms_types %}

            <div class="room_type">
                {% if room.id == 'rooms_types-0' %}
                    <div class="content">
                        <i class="ri-global-line"></i>
                        <ul>
                            <li>Chatroom wil be public</li>
                            <li>Everybody can join to this room</li>
                            <li>Chatroom will appear at global chat</li>
                            <li>External people can see the chat</li>
                        </ul>
                    </div>

                 {% else %}
                    <div class="content">

                        <i class="ri-lock-fill"></i>
                        <ul>
                            <li>Chatroom wil be private</li>
                            <li>Only people with key can join to this chat room</li>
                            <li>Chatroom will be show only if you are in member </li>
                            <li>External people can not see chat</li>
                        </ul>
                    </div>
                {% endif %}
                {{ room}}


                {{ room.label(class="custom-radio") }}
            </div>
            {% endfor %}

            <div class="room__category">
                {% for category in form.category %}
                    <div>
                    {{ category }}
                    {{ category.label }}

                    </div>
                {% endfor %}
            </div>

        </div>
        {{ form.submit(class="create_room-submit") }}


    </form>

{% endblock main %}

R