app/rooms/models.py
# local modules and libraries
from app import db


# models
class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.INTEGER, primary_key=True, nullable=False)
    name = db.Column(db.VARCHAR(50), nullable=False)
    description = db.Column(db.TEXT)
    room = db.relationship('Room', backref='Category', lazy=True)

    def __repr__(self):
        return f'Category: {self.name}'


class Room(db.Model):
    __tablename__ = 'room'
    id = db.Column(db.VARCHAR(100), primary_key=True, nullable=False)
    title = db.Column(db.VARCHAR(80), index=True, nullable=False)
    description = db.Column(db.TEXT)
    image_url = db.Column(db.TEXT)
    likes = db.Column(db.INTEGER)
    room_key = db.Column(db.VARCHAR(40), unique=True)
    is_private = db.Column(db.Boolean, nullable=False , default=False)
    category = db.Column(db.INTEGER,
                         db.ForeignKey('category.id', ondelete='cascade',
                                       onupdate='cascade'),
                         nullable=False)
    rooms_pool = db.relationship('RoomsPool', backref='Room')

    def __repr__(self):
        return f'Room: {self.title}'


class Roles(db.Model):
    __tablename__ = "roles"
    id = db.Column(db.INTEGER, primary_key=True, nullable=False)
    name = db.Column(db.VARCHAR(120), nullable=False)
    description = db.Column(db.TEXT)
    rooms_pool = db.relationship('RoomsPool', backref='Roles')

    def __repr__(self):
        return f'Role: {self.name}'


class RoomsPool(db.Model):
    __tablename__ = 'roomspool'

    id = db.Column(db.INTEGER, primary_key=True, nullable=False)
    room_id = db.Column(db.VARCHAR(100), db.ForeignKey('room.id', ondelete='restrict'), nullable=False)
    user_id = db.Column(db.INTEGER, db.ForeignKey('user.id', ondelete='restrict'), nullable=False)
    role_id = db.Column(db.INTEGER, db.ForeignKey('roles.id', ondelete='restrict'), nullable=False)

    def __repr__(self):
        return f"""room_id : {self.room_id}
                   user_id : {self.user_id}
                   role_id: {self.role_id}   
        """

app/rooms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, RadioField, SubmitField, TextAreaField
from flask_wtf.file import FileField, FileRequired
from wtforms.validators import DataRequired
from flask import current_app
from .models import Category



class CreateRoom(FlaskForm):
    title = StringField('Chatroom title', validators=[DataRequired()])
    image = FileField("Upload chatroom image")
    description = TextAreaField('description', validators=[DataRequired()])
    rooms_types = RadioField(choices=[('Chatroom wil be public', 'public'), ('value2', 'private')])
    category = RadioField()

    submit = SubmitField('Create chatroom')

app/__init__.py
# Third party libraries
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

# local modules and libraries
from configs import config

# globals
db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.register'
    login_manager.login_message = "You must be logged in to access this page."
    migrate = Migrate(app, db)

    from app.rooms import models
    from app.auth import models

    from .home.views import home as home_blueprint
    from .rooms.views import rooms as rooms_blueprint
    from .auth.views import auth as auth_blueprint
    from .profile.views import user_profile as user_profile_blueprint

    app.register_blueprint(home_blueprint)
    app.register_blueprint(rooms_blueprint)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(user_profile_blueprint)

    return app

app/home/views.py
# Third party libraries
from flask import Blueprint, render_template, request

# local libraries and modules
from ..rooms.models import Category, Room
from ..rooms.utils import get_user_rooms

home = Blueprint('home', __name__, static_folder='static',
                 template_folder='templates',
                 static_url_path='/home/static')




@home.route('/', methods=['GET', 'POST'])
def main_content():
    categories = Category.query.all()
    rooms = Room.query.filter_by(category=1).all()
    user_rooms = get_user_rooms()
    if request.method == 'POST':
        rooms = Room.query.filter_by(category=str(*request.form)).all()
    return render_template('home.html', categories=categories, rooms=rooms, user_rooms=user_rooms)

app/profile/views.py
# third party libraries
from flask import Blueprint, render_template

from flask_login import login_required
# local imports
from ..rooms import utils

user_profile = Blueprint('user_profile', __name__,
                         static_folder='static', template_folder='templates',
                         static_url_path='/profile/static')


@user_profile.route('/profile')
@login_required
def profile():
    created_rooms = utils.get_user_rooms()
    return render_template("profile.html", rooms=created_rooms, user_rooms=created_rooms)

app/rooms/views.py
# third party libraries
import os.path

from flask import Blueprint, render_template, abort, flash
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from .forms import CreateRoom
# local modules and libraries
from .models import Room, Category, RoomsPool
from .utils import generate_room_key
from app import db

rooms = Blueprint('rooms', __name__, static_folder='static',
                  template_folder='templates',
                  static_url_path='/chatrooms')


@rooms.errorhandler(404)
def page_not_found(error):
    return render_template('404.html', title='404'), 404


@rooms.route('/chatrooms/<room_id>')
@login_required
def room(room_id):
    room_data = Room.query.filter_by(id=room_id).first()

    if room_data is None:
        abort(404)
    return 'hi there'


@rooms.route('/chatrooms/create_room', methods=['GET', 'POST'])
@login_required
def create_room():
    filename = ""
    form = CreateRoom()
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]
    if form.validate_on_submit():
        print(form.category.data)
        room_key = generate_room_key()
        image = form.image.data
        filename = secure_filename(image.filename)
        new_filename = room_key + "-" + filename
        print(new_filename)
        image.save(os.path.join(
            rooms.static_folder, 'images', new_filename
        ))

        room = Room(id=form.title.data,
                    title=form.title.data,
                    description=form.description.data,
                    image_url=new_filename,
                    room_key=room_key,
                    category=form.category.data,
                    is_private=True if form.rooms_types.data == 'private' else False
                    )
        rooms_pool = RoomsPool(room_id=form.title.data,
                               user_id=current_user.id,
                               role_id=1)

        db.session.add_all([room, rooms_pool])
        db.session.commit()
        print("you have created a new chatroom")

    return render_template('create_chatroom.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/globals.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/header.css') }}">

    {% block links %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <!-- =============== HEADER =============== -->
    {% block header %}
    <header class="header">
        <div class="header__brand ">
            <a href="{{ url_for('home.main_content') }}">
                <i class="ri-door-open-fill"></i>
                <span>ChatRoom</span>
            </a>
        </div>
        <nav class="header__navbar">
            <ul class="navbar__list">
                <li class="list__item">
                    <a class="list_link" href="{{ url_for('home.main_content') }}">
                        <i class="ri-home-line"></i>
                        <span>Home</span>
                    </a>
                </li>
                <li class="list__item">
                    <a class="list_link" href="{{ url_for('rooms.create_room') }}">
                        <i class="ri-add-circle-fill"></i>
                        Create
                    </a>
                </li>
                <li class="list__item">
                    <a class="list_link" href="#">
                        <i class="ri-search-line"></i>
                        Rooms
                    </a>
                </li>
                <li class="list__item">
                    <a class="list_link" href="{{ url_for('user_profile.profile') }}">
                        <i class="ri-user-fill"></i>
                        Profile
                    </a>
                </li>
            </ul>
        </nav>
        <div class="header__actions">
            <i class="ri-notification-2-fill action"></i>
            <i class="ri-moon-fill action"></i>
        </div>
    </header>
    {% endblock %}

    <!-- =============== MAIN CONTENT =============== -->
    {% block main %}

    {% endblock %}

    <!-- =============== FOOTER =============== -->
    {% block footer %}

    {% endblock %}

    <!-- =============== MAIN SCRIPTS =============== -->
    {% block scripts %}{% endblock %}
    <script src="{{ url_for('static', filename='scripts/header.js') }}"></script>
</body>



</html>